_BASE_: "../Base-DeepLesion-RCNN-VoVNet-FPN.yaml"
MODEL:
  WEIGHTS: "/mnt/users/.cache/torch/checkpoints/vovnet57_ese_detectron2.pth"
  MASK_ON: True
  VOVNET:
    CONV_BODY : "V-57-eSE"
SOLVER:
  STEPS: (60000, 80000)
  MAX_ITER: 90000
OUTPUT_DIR: "/checkpoints/MRCN-V2-57-1x"