_BASE_: "../Base-RCNN-VoVNet-FPN.yaml"
MODEL:
  WEIGHTS: "/home/wangcheng/ms-project/checkpoints/vovnet39_ese_detectron2.pth"
  MASK_ON: True
  VOVNET:
    CONV_BODY : "V-39-eSE"
SOLVER:
  STEPS: (120000, 160000)
  MAX_ITER: 180000
OUTPUT_DIR: "MRCN-V2-39-2x"
