_BASE_: "../Base-DeepLesion-RCNN-VoVNet-FPN.yaml"
MODEL:
  USE_3D_FUSION: True
  WEIGHTS: "/mnt/users/.cache/torch/checkpoints/vovnet57_ese_detectron2.pth"
  MASK_ON: True
  VOVNET:
    CONV_BODY : "V-57-eSE"
  BACKBONE:
    IN_CHANNELS: 256
    OUT_CHANNELS: 256
SOLVER:
  STEPS: (60000, 80000)
  MAX_ITER: 90000
#  STEPS: (210000, 250000)
#  MAX_ITER: 270000
OUTPUT_DIR: "/checkpoints/MRCN-V2-57-1x-3dce"
