INPUT:
#  SLICE_NUM: 9
#  Z_FLIP_PROB_TRAIN: 0.5
#  MIN_SIZE_TRAIN: (400, 600, 800, 1000, 1200)
#  MAX_SIZE_TRAIN: 1200
  IGNORE_EMPTY: True

  NORM_SPACING: .8
  MAX_IM_SIZE: 512
  IMG_DO_CLIP: True
  SLICE_INTV: 2
  NUM_SLICES: 3  # multi-slice input (data-level fusion in 3DCE paper) to incorporate 3D context
  NUM_IMAGES_3DCE: 3
  WINDOWING: [-1024, 1050]

  DATA_AUG_SCALE: [.8, 1.2]
  DATA_AUG_3D: -0.5
  DATA_AUG_POSITION: True
  IMAGE_MEAN: 50.
MODEL:
  PIXEL_MEAN: [ 0., 0., 0., 0., 0., 0., 0., 0., 0. ]
  PIXEL_STD: [ 1., 1., 1., 1., 1., 1., 1., 1., 1. ]
  META_ARCHITECTURE: "GeneralizedRCNN"
  BACKBONE:
    NAME: "build_vovnet_fpn_backbone"
    FREEZE_AT: 0
  VOVNET:
    OUT_FEATURES: [ "stage2", "stage3", "stage4", "stage5" ]
  FPN:
    IN_FEATURES: ["stage2", "stage3", "stage4", "stage5"]
  ANCHOR_GENERATOR:
    SIZES: [ [ 16 ], [ 32 ], [ 64 ], [ 128 ], [ 256 ] ]  # One size for each in feature map
    ASPECT_RATIOS: [ [ 0.5, 1.0, 2.0 ] ]  # Three aspect ratios (same for all in feature maps)
  RPN:
    IN_FEATURES: [ "p2", "p3", "p4", "p5", "p6" ]
    PRE_NMS_TOPK_TRAIN: 2000  # Per FPN level
    PRE_NMS_TOPK_TEST: 1000  # Per FPN level
    # Detectron1 uses 2000 proposals per-batch,
    # (See "modeling/rpn/rpn_outputs.py" for details of this legacy issue)
    # which is approximately 1000 proposals per-image since the default batch size for FPN is 2.
    POST_NMS_TOPK_TRAIN: 1000
    POST_NMS_TOPK_TEST: 100
  ROI_HEADS:
    NAME: "StandardROIHeads"
    IN_FEATURES: [ "p2", "p3", "p4", "p5" ]
    BATCH_SIZE_PER_IMAGE: 512
    NMS_THRESH_TEST: 0.1
  ROI_BOX_HEAD:
    NAME: "FastRCNNConvFCHead"
    NUM_FC: 2
    POOLER_RESOLUTION: 7
  ROI_MASK_HEAD:
    NAME: "MaskRCNNConvUpsampleHead"
    POOLER_SAMPLING_RATIO: 2
    NUM_CONV: 4
    POOLER_RESOLUTION: 14
DATASETS:
  TRAIN: ("coco_deeplesion_train", "coco_deeplesion_val",)
  TEST: ("coco_deeplesion_test",)
SOLVER:
  IMS_PER_BATCH: 16
  BASE_LR: 0.01
  WEIGHT_DECAY: 0.0001
  CLIP_GRADIENTS:
    ENABLED: True
    CLIP_VALUE: 10.0
TEST:
  DETECTIONS_PER_IMAGE: 100
#VIS_PERIOD: 10
VERSION: 2
